"""Room schema v1: the closed vocabulary every room is checked against."""

SCHEMA_VERSION = 1

CORE_FILES = ("_meta.md", "STATE.md", "MEMORY.md", "AGENDA.md", "manifest.json")
CORE_DIRS = ("log", "runbooks", "memory")

OPTIONAL_DIRS = ("events", "incidents", "bugs", "plans", "releases", "comms", "specs",
                 "evidence", "reference", "archive", "tenants", "_scratch")
OPTIONAL_FILES = ("ACCESS.md", "README.md")

# present in many repos, never a shelf, never a violation
TOLERATED = (".git", ".gitignore", ".gitkeep", ".DS_Store", ".claude", ".codex", ".serena",
             "_index.json", ".cwi", "CLAUDE.md", "AGENTS.md", "GEMINI.md", ".cursorrules")

FRONTMATTER_KIND = {"_meta.md": "meta", "STATE.md": "state", "MEMORY.md": "memory", "AGENDA.md": "agenda"}

KINDS = ("studio", "product", "client", "kit", "rsi", "tenant")
AUDIENCES = ("studio", "client", "public")
CADENCES = ("living", "snapshot", "ledger", "append")
ROOM_MODES = ("repo", "embedded")

# top-level groups of the CWI tree; operation-room is the studio room beside them
GROUPS = ("products", "kits", "rsi", "clients", "exp")
STUDIO_ROOM = "operation-room"
ARCHIVE = "archive"

GENERATED_MARK = "<!-- GENERATED by cwi ws meta"

# names allowed loose at the tree root and inside a group folder
ROOT_ALLOWED = {"_meta.md", "CLAUDE.md", "AGENTS.md", ".DS_Store", ".claude", ".codex"}
GROUP_ALLOWED = {"_meta.md", ".DS_Store"}
# generated or tolerated at a workspace root, outside any repository
WS_ALLOWED = {"_meta.md", "CLAUDE.md", "AGENTS.md", ".DS_Store", ".gitignore", ".claude", ".codex", ".cwi", "_scratch"}

SKIP_DIRS = {"node_modules", ".venv", "venv", "__pycache__", ".git", ".pytest_cache", ".next", "dist", "build"}
